# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

def sum_even_fibonacci(max_num):
    n1 = 1
    n2 = 2
    sum = 0
    # print(n1)
    while n2 < max_num:
        if n2 % 2 == 0:
            sum += n2
        #     print(f'{n2} added')
        # else:
        #     print(f'{n2} not added')
        new_n = n2 + n1
        n1 = n2
        n2 = new_n
    return sum

print(sum_even_fibonacci(4000000))